# Workflow [No identation required for naming the workflow]
# Should Have Name
name: Hello

# On tells when the workflow should run (Give identation by tab)
on: 
  workflow_dispatch: 
# Jobs
# Should be inside the workflow

# Job tells what the workflow should do, there can be one or more than one jobs, hence we write Jobs
# jobs is an object so needs identation

jobs:
  # first Job (give identation)
  say-hello:  
    # Creates an Ephermal Container with Ubuntu running
    runs-on: ubuntu-latest
    # That ephermal container will have steps to execute, hence name those steps and use run: run has the command
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"

# Steps
# Should be inside the Job

# Actions
# Should be inside the Steps
