name: hello

on: 
  schedule:
    - cron: '*/6 * * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Greeting message
        run: echo "Hello grom Github Actions!"

      - name: Checking current Date and Time
        run: date

      - name: List the files in the repo
        run: ls -la

      - name: Print the name of the branch that triggered the run
        run: echo "${{ github.ref_name }}"

      - name: Print the runner's operating system
        run: echo "The operating system is ${{ runner.os }}"

      
