name: matrix

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
        
        exclude: 
         - os: windows-latest
         - python-version: "3.10"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display Python Version
        run: python --version

      - name: Error to check for macos
        if: matrix.os == 'macos-latest'
        run: exit 1
        
