name : Shubham Deshmukh
role : DevOps Engineer
exeperince_years : 1
learning : true


tools:
  - Docker
  - Linux
  - Jenkins
  - Kubernetes
  - GitHub
  
Hobbies: [treaking, bike riding, playing cricket]
