name: Python CI Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Python Version
        run: python --version

      - name: Run Python Script
        run: python scripts/hello.py