name: runner

on: workflow_dispatch

jobs:
    runner_ubuntu:
        runs-on: ubuntu-latest

        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"
    
    runner_windows:
        runs-on: windows-latest

        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"

    runeer_macOs:
        runs-on: macos-latest

        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"