name: runner

on: workflow_dispatch

jobs:
    runner_ubuntu:
        runs-on: ubuntu-latest
        
        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"
            
            - name: Verify version installed or not
              run: |
                echo "== Docker Version =="
                docker --version

                echo "== Python Version =="
                python --version

                echo "== Git Version =="
                git --version

                echo "== Node Version =="
                node --version
                npm --version

    runner_windows:
        runs-on: windows-latest

        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"

    runeer_macOs:
        runs-on: macos-latest

        steps:
            - name: Display OS Name
              run: echo "The operating system is ${{ runner.os }}"