name: Secrets

on: workflow_dispatch

jobs:
    secret_job:
        runs-on: ubuntu-latest

        steps:
            - name: To check secret is working
              env:
                MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE}}
              run: |
                if [ -z "$MY_SECRET_VALUE" ]; then
                  echo "The secret is set: false"
                else
                  echo "The secret is set: true"
                fi
            
            - name: Display the secret
              env:
                SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"