name: Secrets

on: workflow_dispatch

jobs:
    secret_job:
        runs-on: ubuntu-latest

        steps:
            - name: Display the secret
              env:
                MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE}}
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"