name: self_hosted

on: workflow_dispatch

jobs:
    test:
        runs-on: [self-hosted, my-linux-runner]

        steps:
            - name: Display hostname of the machine
              run: hostname

            - name: Working directory
              run: pwd

            - name: Create a file  
              run: touch test.txt
              
            - name: Vefify file exits
              run: ls -l